### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by MasterWindowS** [CS2Browser/Launcher#10]
Hi, I'm sorry to ask this question but I'm a bit new to this. I wanted to add my server and I'm supposed to edit the listserver.json, I already added my server and so on, I also did the fastdl and well. my question is, how do I compile everything to make the application? because apparently it is an application.

**Comment by JMorell** [comment]
Hello, you don't need to compile anything, you should upload a PR (in github) for us to add your server to the global list so that all players can see your server.

**Comment by MasterWindowS** [comment]
Oh, thanks you <3
