### ISSUE TITLE
Downloading assets from wrong server

### ISSUE THREAD

**Issue by xLeviNx** [CS2Browser/Launcher#11]
Often it downloads the assets from the wrong server. Need to select Download Assets again for it to download it from the right server on the list

**Comment by JMorell** [comment]
Yesterday I identified this error but it only happens with the maps right?, this afternoon I will solve it.

**Comment by xLeviNx** [comment]
> Yesterday I identified this error but it only happens with the maps right?, this afternoon I will solve it.

Yes - its often sporadic and not reproducible all the time.
