### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by xLeviNx** [CS2Browser/Launcher#12]
Implement a refresh button to load out servers  map name, player/maxplayer. I'm sure this could be also rate limited

**Comment by JMorell** [comment]
You have this button:

![image](https://github.com/CS2Browser/Launcher/assets/6134888/427a6ebb-cd64-44bb-b076-3bea3ca6dc9c)

**Comment by xLeviNx** [comment]
silly me - ignore
