### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rcon420** [CS2Browser/Launcher#3]
Hey! made my own build everything looks good but maybe could explain why its attempting to download default maps?
maps/de_vertigo.vpk 0KB downloading...
maps/de_nuke.vpk 0KB downloading...
maps/de_inferno.vpk 0KB downloading...
maps/de_mirage.vpk 0KB downloading...
maps/awp_lego_2_ultimate.vpk 73MB downloading...
maps/awp_lego_2_ultimate.vpk download complete

i  did not  specify in the .txt to download default maps, went thru the code but couldn't figure it out why its attempting to download defautl maps.

**Comment by JMorell** [comment]
It automatically tries to download the map that is currently on the server, in the fastdl you do not have to put the maps, otherwise the user has to download a lot of content at once.
